depends_on:
  - test

when:
  - event: tag
  - event: pull_request

steps:
  pack-chart:
    image: alpine/helm:3.16.4
    commands:
      - helm package --version "${CI_COMMIT_TAG#v}" -d /tmp/ charts/woodpecker

  release-chart:
    image: alpine:3.21
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands: |
      apk add -q --no-cache curl jq

      UPLOAD_URL=$(curl -s --user woodpecker-bot:$GITHUB_TOKEN -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$CI_REPO_OWNER/$CI_REPO_NAME/releases -d "{\"tag_name\":\"${CI_COMMIT_TAG#v}\",\"name\":\"helm-woodpecker-${CI_COMMIT_TAG#v}\",\"body\":\"A Helm chart for Woodpecker CI\"}" | jq -r .upload_url | sed -e "s/{?name,label}//")

      curl -v --user woodpecker-bot:$GITHUB_TOKEN -X POST --header "Content-Type: application/gzip" --data-binary @/tmp/woodpecker-${CI_COMMIT_TAG#v}.tgz "$UPLOAD_URL?name=woodpecker-${CI_COMMIT_TAG#v}.tgz"
    when:
      - event: tag

  release-chart-ghcr:
    image: alpine/helm:3.16.4
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - echo $GITHUB_TOKEN | helm registry login ghcr.io --username ignored --password-stdin
      - helm push /tmp/woodpecker-${CI_COMMIT_TAG}.tgz oci://ghcr.io/woodpecker-ci/helm
    when:
      - event: tag

  update-readme:
    image: docker.io/jnorwood/helm-docs:v1.14.2
    commands:
      - helm-docs
      - cat charts/woodpecker/README.md

  prettier:
    image: docker.io/jauderho/prettier:3.4.2
    commands:
      - prettier -w .

  push-readme:
    image: docker.io/appleboy/drone-git-push:1.1.1
    settings:
      remote: ssh://git@github.com/woodpecker-ci/helm.git
      branch: main
      commit: true
      ssh_key:
        from_secret: BOT_PRIVATE_KEY
      commit_message: '[skip ci] Update README.md'
    when:
      - event: tag
